line-length = 100
indent-width = 4

[lint]
select = [
    "E4", "E7", "E9", "F",  # PyFlakes
    "I",   # isort
    "B",   # Bugbear
    "UP",  # PyUpgrade
    "A",   # builtins
    "C4",  # flake8-comprehensions
    "EM",  # flake8-errmsg
    "G",   # flake8-logging-format
    "RET", # flake8-return
    "PD",  # pandas-vet
    "RUF", # Ruff-specific rules
]
